### PR TITLE
Adding module support for Commonjs, AMD or Browser

### PR DESCRIPTION
**Pull request by webzfactory**
Please take note that no change have been made to your code and your tests will pass just as before. But now this module can be used with either Commonjs module pattern or AMD. 

The code added is based on this SO question : 
http://stackoverflow.com/questions/13673346/supporting-both-commonjs-and-amd

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Please create an issue first before taking the effort to do this. I'm almost 100% sure this won't get merged, but I let @sindresorhus make the call.

You can always use webpack or browserify if you want to use this in your browser.

**Comment by webzfactory** [comment]
I understand my mistake. 

For people using TypeScript in Visual Studio and not wanting a dependency on webpack or browserify this does the trick, and I assume (I can be terribly wrong ) it wont brake for people using browserify either.

I will create an issue tomorow. Thank you.

**Comment by SamVerschueren** [comment]
> For people using TypeScript in Visual Studio and not wanting a dependency on webpack or browserify this does the trick

I'm afraid this is something that should be resolved by the user of the module, not by the module itself. It adds extra overhead and it made the code much worse in terms of readability and thus maintainability.

> I will create an issue tomorow.

No need to, now it can be discusses in the PR :)

**Comment by kevva** [comment]
Originally, we supported AMD but removed support in https://github.com/sindresorhus/object-assign/commit/6e57ecf8e9c27b1de90c03e718879a372d9360ad.

**Comment by sindresorhus** [comment]
No thanks.

Here's a standalone version you can run directly in the browser: https://wzrd.in/standalone/object-assign

**Comment by webzfactory** [comment]
Ok guys. 

My interest here was to have a module that can be used with AMD(requirejs). 

Maybe you are right and an extra dependency on browserify is better that the overhead and poor readability introduced by this change. 

Thanks.

**Pull request closed without merging**
