### PR TITLE
Add inline MIT license with @license marker

### PR DESCRIPTION
**Pull request by gaearon**
This allows us to easily preserve it in React builds. This is the first part of fixing #44 and https://github.com/facebook/react/issues/8789 (the second change needs to be done in React repo).

### CODE REVIEW

**Comment by gaearon** [comment]
Actually this adds a whole KB to the minified build. There must be a shorter version..

**Comment by SamVerschueren** [comment]
Just wondering, wouldn't it be possible for the bundler to read the `license` file and prepend it instead of having module maintainers having to add it inline?

**Comment by gaearon** [comment]
In theory, yes, but I’m not aware of bundlers doing this in practice.

**Comment by gaearon** [comment]
Replaced with a shorter version ([Angular is doing it](https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js) so that should be fine).

**Comment by gaearon** [comment]
Okay, this should be ready for review.

**Comment by sindresorhus** [comment]
I don't think this module should have to change just because React needs it. I know of no node modules that include the license in the source code. However, I'm gonna merge this as the license stuff has already wasted too much of people's time.

**Comment by gaearon** [comment]
Thanks, I truly appreciate it.

**Comment by sindresorhus** [comment]
Published as 4.1.1

**Pull request merged**
