### PR TITLE
tiny optimizations

### PR DESCRIPTION
**Pull request by stevenvachon**

### CODE REVIEW

**Comment by stevenvachon** [comment]
Tests pass locally (?)

**Comment by sindresorhus** [comment]
No thanks. V8 optimizes that away for us.

**Comment by stevenvachon** [comment]
Not according to jspef.

**Comment by floatdrop** [comment]
@stevenvachon you can easily check it out: https://gist.github.com/floatdrop/f600d41a740cbcb63b15

I get about same results in both cases (~30,500 ops/s).

**Comment by stevenvachon** [comment]
http://jsperf.com/array-length-vs-cached/37

**Pull request closed without merging**
